modLoader="javafml"
loaderVersion="[${forge_loader_version},${next_forge_loader_version})"
license="${mod_license}"
issueTrackerURL="${mod_url_issues}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="${mod_url_home}"
#logoFile="logo-forge.png"
credits="${mod_credits}"
authors="${mod_authors}"
displayTest="MATCH_VERSION"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},${next_minecraft_version})"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},${next_forge_version})"
ordering="NONE"
side="BOTH"
